services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data

  make:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    entrypoint: [ "make" ]

  watchfiles:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    entrypoint: [ "sh", "-c", "watchfiles make *.md" ]
